# Site settings
title: Aidan Bevan
description: Certified Junior Gymnastics Coach specializing in early childhood development and inclusive training for young children of all abilities in South Africa.
baseurl: ""
url: "https://aidanbevan.com"
author:
  name: Aidan Bevan
  email: aidanbevan09@gmail.com

# Social Media
social:
  name: Aidan Bevan
  links: []

# SEO Settings
logo: /assets/images/gymnast.png
locale: en_ZA

# Location
location:
  city: Pinetown
  region: KwaZulu-Natal
  country: South Africa

# Build settings
markdown: kramdown

# SASS/SCSS settings
sass:
  sass_dir: assets/css
  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - node_modules
